
typedef NS_ENUM(NSInteger, MPOS_RESULT){
    MPOS_SUCCESS                        = 0,
    MPOS_SUCCESS_ALREADY_OPEN           = 1,
    MPOS_FAIL                           = 1000,
    MPOS_FAIL_INVALID_INTERFACE         = 1001,
    MPOS_FAIL_NO_OPEN                   = 1002,
    MPOS_FAIL_NOT_SUPPORT               = 1003,
    MPOS_FAIL_INVALID_PARAMETER         = 1004,
    MPOS_FAIL_NO_RESPONSE               = 1005,
    MPOS_FAIL_NOT_CONNECT               = 1006,
    MPOS_FAIL_NO_DEVICE                 = 1007,
    MPOS_FAIL_NO_FILE                   = 1008,
    MPOS_FAIL_NOT_SUPPORT_CODEPAGE      = 1012,
    MPOS_FAIL_NOT_SUPPORT_ICS           = 1013,
    MPOS_PAGEMODE_ALREADY_IN            = 1014,
    MPOS_TRANSACTION_ALREADY_IN         = 1015,
    MPOS_FAIL_NOT_SUPPORT_ESCSEQ        = 1017,

    RES_SUCCESS                         = 0,
    RES_SUCCESS_ALREADY_OPEN            = 1,
    RES_FAIL                            = 1000,
    RES_INVALID_INTERFACE               = 1001,
    RES_NO_OPEN_DEVICE                  = 1002,
    RES_NOT_SUPPORT                     = 1003,
    RES_INVALID_PARAM                   = 1004,
    RES_NO_RESPONSE                     = 1005,
    RES_CONNECT_FAIL                    = 1006,
    RES_NO_DEVICE                       = 1007,
    RES_NO_FILE                         = 1008,
    RES_NOT_SUPPORT_CODEPAGE            = 1012,
    RES_NOT_SUPPORT_ICS                 = 1013,
    RES_PAGEMODE_ALREADY_IN             = 1014,
    RES_TRANSACTION_ALREADY_IN          = 1015,
    RES_NOT_SUPPORT_ESCSEQ              = 1017,
    RES_MSR_NOT_READY                   = 1018,
    
    RES_NO_DEVICE_FOUND                 = 5000,
    RES_NO_PERMISSION                   = 5001,
    RES_DECODE_FAIL                     = 5003,
};
